version: '3.8'

services:
  ga-scheduler:
    image: ga-scheduler-image
    container_name: ga-scheduler-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/Desktop:/app/outputs