version: '3.8'

services:
  genetic-algorithm-auto-scheduler:
    image: genetic-algorithm-auto-scheduler-image-image
    container_name: genetic-algorithm-auto-scheduler-image-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $(pwd)/outputs:/app/outputs
      - $(pwd)/proposals/csv/ObsList1737538994939.csv:/app/proposals/csv/ObsList1737538994939.csv