version: '3.8'

services:
  auto-scheduler-backend-service:
    image: auto-scheduler-backend-image
    container_name: auto-scheduler-backend-container
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/output:/app/output