version: '3.8'

services:
  auto-scheduler-backend-service:
    image: auto-scheduler-backend-image
    container_name: auto-scheduler-backend-container
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/outputs:/app/outputs
      - ./backend/proposals/csv/ObsList.csv:/app/proposals/csv/ObsList.csv